Created using Colaboratory
TanyaShamis1710/my_repo1 pull request #2
Opened 2019-10-01 04:40 UTC by TanyaShamis1710

2019-10-01 06:02 UTC, illarionovEA requested changes
файл с ошибками и не все задание

2019-10-13 12:51 UTC, illarionovEA commented
This branch has conflicts that must be resolved (см ниже на странице пулл-реквеста)

2019-12-06 15:49 UTC, illarionovEA approved these changes

2019-12-23 13:03 UTC, TanyaShamis1710 commented
Почему-то не объединяются ветки, хотя вы апрув получен

2019-12-23 13:11 UTC, merged